### PR TITLE
Add the ability to restore the original JSON.parse

### PR DESCRIPTION
**Pull request by alonbrody**
@kensaggy @alonweissfeld Thanks

### CODE REVIEW

**Review by kensaggy — APPROVED** [review]
Notice that after merging it still needs to be published to `npm`

**Review by alonweissfeld — APPROVED** [review]

**Comment by alonbrody** [comment]
@kensaggy @alonweissfeld I know you approved it already but I made another change. After speaking with AlonW we've decided to not override immediately on require in this version and we will change all the relevant places in our code to support this change.

Please verify again

**Review by alonweissfeld — CHANGES_REQUESTED** [review]
@alonbrody You forgot to call `override` in the test file :)

**Comment by alonbrody** [comment]
@alonweissfeld done. Good catch

**Review by alonweissfeld — APPROVED** [review]

**Pull request merged**
